# Generated by Django 3.0.6 on 2020-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_auto_20200505_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='registration_date',
            field=models.DateTimeField(help_text='You will be contacted for the exact time', verbose_name='Registration date to the doctor'),
        ),
    ]
